// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_agent is a generated GoMock package.
package mock_agent

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	pb "github.com/meshplus/bitxhub-model/pb"
	go_bitxhub_client "github.com/meshplus/go-bitxhub-client"
	reflect "reflect"
)

// MockAgent is a mock of Agent interface
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
}

// MockAgentMockRecorder is the mock recorder for MockAgent
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// Appchain mocks base method
func (m *MockAgent) Appchain() (*go_bitxhub_client.Appchain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Appchain")
	ret0, _ := ret[0].(*go_bitxhub_client.Appchain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Appchain indicates an expected call of Appchain
func (mr *MockAgentMockRecorder) Appchain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Appchain", reflect.TypeOf((*MockAgent)(nil).Appchain))
}

// SyncMerkleWrapper mocks base method
func (m *MockAgent) SyncMerkleWrapper(ctx context.Context) (chan *pb.MerkleWrapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMerkleWrapper", ctx)
	ret0, _ := ret[0].(chan *pb.MerkleWrapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncMerkleWrapper indicates an expected call of SyncMerkleWrapper
func (mr *MockAgentMockRecorder) SyncMerkleWrapper(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMerkleWrapper", reflect.TypeOf((*MockAgent)(nil).SyncMerkleWrapper), ctx)
}

// GetMerkleWrapper mocks base method
func (m *MockAgent) GetMerkleWrapper(begin, end uint64) (chan *pb.MerkleWrapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerkleWrapper", begin, end)
	ret0, _ := ret[0].(chan *pb.MerkleWrapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerkleWrapper indicates an expected call of GetMerkleWrapper
func (mr *MockAgentMockRecorder) GetMerkleWrapper(begin, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerkleWrapper", reflect.TypeOf((*MockAgent)(nil).GetMerkleWrapper), begin, end)
}

// SendTransaction mocks base method
func (m *MockAgent) SendTransaction(tx *pb.Transaction) (*pb.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", tx)
	ret0, _ := ret[0].(*pb.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction
func (mr *MockAgentMockRecorder) SendTransaction(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockAgent)(nil).SendTransaction), tx)
}

// SendIBTP mocks base method
func (m *MockAgent) SendIBTP(ibtp *pb.IBTP) (*pb.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendIBTP", ibtp)
	ret0, _ := ret[0].(*pb.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendIBTP indicates an expected call of SendIBTP
func (mr *MockAgentMockRecorder) SendIBTP(ibtp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendIBTP", reflect.TypeOf((*MockAgent)(nil).SendIBTP), ibtp)
}

// GetIBTPByID mocks base method
func (m *MockAgent) GetIBTPByID(id string) (*pb.IBTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIBTPByID", id)
	ret0, _ := ret[0].(*pb.IBTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIBTPByID indicates an expected call of GetIBTPByID
func (mr *MockAgentMockRecorder) GetIBTPByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIBTPByID", reflect.TypeOf((*MockAgent)(nil).GetIBTPByID), id)
}

// GetChainMeta mocks base method
func (m *MockAgent) GetChainMeta() (*pb.ChainMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainMeta")
	ret0, _ := ret[0].(*pb.ChainMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainMeta indicates an expected call of GetChainMeta
func (mr *MockAgentMockRecorder) GetChainMeta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainMeta", reflect.TypeOf((*MockAgent)(nil).GetChainMeta))
}
