// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package peermgr

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_APPCHAIN         Message_Type = 0
	Message_APPCHAIN_ACK     Message_Type = 1
	Message_INTERCHAIN       Message_Type = 2
	Message_INTERCHAIN_ACK   Message_Type = 3
	Message_RULE             Message_Type = 4
	Message_RULE_ACK         Message_Type = 5
	Message_QUERY_IBTP       Message_Type = 6
	Message_QUERY_IBTP_ACK   Message_Type = 7
	Message_IBTP             Message_Type = 8
	Message_IBTP_ACK         Message_Type = 9
	Message_IBTP_RECEIPT     Message_Type = 10
	Message_IBTP_RECEIPT_ACK Message_Type = 11
)

var Message_Type_name = map[int32]string{
	0:  "APPCHAIN",
	1:  "APPCHAIN_ACK",
	2:  "INTERCHAIN",
	3:  "INTERCHAIN_ACK",
	4:  "RULE",
	5:  "RULE_ACK",
	6:  "QUERY_IBTP",
	7:  "QUERY_IBTP_ACK",
	8:  "IBTP",
	9:  "IBTP_ACK",
	10: "IBTP_RECEIPT",
	11: "IBTP_RECEIPT_ACK",
}

var Message_Type_value = map[string]int32{
	"APPCHAIN":         0,
	"APPCHAIN_ACK":     1,
	"INTERCHAIN":       2,
	"INTERCHAIN_ACK":   3,
	"RULE":             4,
	"RULE_ACK":         5,
	"QUERY_IBTP":       6,
	"QUERY_IBTP_ACK":   7,
	"IBTP":             8,
	"IBTP_ACK":         9,
	"IBTP_RECEIPT":     10,
	"IBTP_RECEIPT_ACK": 11,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=peermgr.Message_Type" json:"type,omitempty"`
	Data                 []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version              []byte       `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_APPCHAIN
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func init() {
	proto.RegisterEnum("peermgr.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "peermgr.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x9d, 0x74, 0x6c, 0xe2, 0x33, 0x86, 0xe1, 0xa1, 0x90, 0x55, 0x28, 0x5d, 0xd5, 0x4d,
	0x16, 0x7a, 0x82, 0x34, 0x0c, 0x18, 0xd4, 0x12, 0x87, 0x54, 0x70, 0x55, 0x22, 0x0e, 0xc5, 0x45,
	0x4d, 0x48, 0xb2, 0xe9, 0x99, 0xbc, 0x87, 0xb8, 0xf4, 0x08, 0x92, 0x93, 0xc8, 0x7b, 0x6d, 0x4d,
	0x77, 0xef, 0xff, 0xff, 0xef, 0x0b, 0x61, 0xe0, 0x62, 0x63, 0xdb, 0xb6, 0x5c, 0xdb, 0xb8, 0x6e,
	0xaa, 0xae, 0x42, 0xb7, 0xb6, 0xb6, 0xd9, 0xac, 0x9b, 0xe9, 0xa7, 0x03, 0xee, 0xe3, 0x6e, 0xc2,
	0x6b, 0x90, 0xdd, 0xb6, 0xb6, 0xa1, 0x98, 0x88, 0x59, 0x70, 0x73, 0x15, 0xef, 0x99, 0x78, 0xbf,
	0xc7, 0xc5, 0xb6, 0xb6, 0x86, 0x11, 0x44, 0x90, 0x6f, 0x65, 0x57, 0x86, 0xce, 0x44, 0xcc, 0x7c,
	0xc3, 0x37, 0x86, 0xe0, 0x3e, 0xdb, 0xa6, 0x7d, 0xaf, 0x3e, 0xc2, 0x11, 0xd7, 0x87, 0x38, 0xfd,
	0x12, 0x20, 0x49, 0x46, 0x1f, 0xbc, 0x24, 0xcf, 0xd3, 0xbb, 0x24, 0x5b, 0xa8, 0x13, 0x54, 0xe0,
	0x1f, 0xd2, 0x2a, 0x49, 0xef, 0x95, 0xc0, 0x00, 0x20, 0x5b, 0x14, 0xda, 0xec, 0x08, 0x07, 0x11,
	0x82, 0x21, 0x33, 0x33, 0x42, 0x0f, 0xa4, 0x59, 0x3e, 0x68, 0x25, 0xe9, 0x6b, 0x74, 0x71, 0x7f,
	0x4a, 0xee, 0xd3, 0x52, 0x9b, 0x97, 0x55, 0x36, 0x2f, 0x72, 0x35, 0x26, 0x77, 0xc8, 0xcc, 0xb8,
	0xe4, 0xf2, 0xea, 0x91, 0xfb, 0xdf, 0x9f, 0xd1, 0x9f, 0x70, 0x32, 0x3a, 0xd5, 0x59, 0x5e, 0x28,
	0xc0, 0x4b, 0x50, 0xc7, 0x0d, 0x73, 0xe7, 0x73, 0xff, 0xbb, 0x8f, 0xc4, 0x4f, 0x1f, 0x89, 0xdf,
	0x3e, 0x12, 0xaf, 0x63, 0x7e, 0xcb, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0xb7, 0xd5,
	0x12, 0x5c, 0x01, 0x00, 0x00,
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMessage(uint64(m.Type))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Message_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = append(m.Version[:0], dAtA[iNdEx:postIndex]...)
			if m.Version == nil {
				m.Version = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
