// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_adapt is a generated GoMock package.
package mock_adapt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pb "github.com/meshplus/bitxhub-model/pb"
)

// MockAdapt is a mock of Adapt interface.
type MockAdapt struct {
	ctrl     *gomock.Controller
	recorder *MockAdaptMockRecorder
}

// MockAdaptMockRecorder is the mock recorder for MockAdapt.
type MockAdaptMockRecorder struct {
	mock *MockAdapt
}

// NewMockAdapt creates a new mock instance.
func NewMockAdapt(ctrl *gomock.Controller) *MockAdapt {
	mock := &MockAdapt{ctrl: ctrl}
	mock.recorder = &MockAdaptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapt) EXPECT() *MockAdaptMockRecorder {
	return m.recorder
}

// GetServiceIDList mocks base method.
func (m *MockAdapt) GetServiceIDList() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceIDList")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceIDList indicates an expected call of GetServiceIDList.
func (mr *MockAdaptMockRecorder) GetServiceIDList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceIDList", reflect.TypeOf((*MockAdapt)(nil).GetServiceIDList))
}

// MonitorIBTP mocks base method.
func (m *MockAdapt) MonitorIBTP() chan *pb.IBTP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorIBTP")
	ret0, _ := ret[0].(chan *pb.IBTP)
	return ret0
}

// MonitorIBTP indicates an expected call of MonitorIBTP.
func (mr *MockAdaptMockRecorder) MonitorIBTP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorIBTP", reflect.TypeOf((*MockAdapt)(nil).MonitorIBTP))
}

// Name mocks base method.
func (m *MockAdapt) Name() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Name indicates an expected call of Name.
func (mr *MockAdaptMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAdapt)(nil).Name))
}

// QueryIBTP mocks base method.
func (m *MockAdapt) QueryIBTP(id string, isReq bool) (*pb.IBTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryIBTP", id, isReq)
	ret0, _ := ret[0].(*pb.IBTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryIBTP indicates an expected call of QueryIBTP.
func (mr *MockAdaptMockRecorder) QueryIBTP(id, isReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryIBTP", reflect.TypeOf((*MockAdapt)(nil).QueryIBTP), id, isReq)
}

// QueryInterchain mocks base method.
func (m *MockAdapt) QueryInterchain(serviceID string) (*pb.Interchain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryInterchain", serviceID)
	ret0, _ := ret[0].(*pb.Interchain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryInterchain indicates an expected call of QueryInterchain.
func (mr *MockAdaptMockRecorder) QueryInterchain(serviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInterchain", reflect.TypeOf((*MockAdapt)(nil).QueryInterchain), serviceID)
}

// SendIBTP mocks base method.
func (m *MockAdapt) SendIBTP(ibtp *pb.IBTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendIBTP", ibtp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendIBTP indicates an expected call of SendIBTP.
func (mr *MockAdaptMockRecorder) SendIBTP(ibtp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendIBTP", reflect.TypeOf((*MockAdapt)(nil).SendIBTP), ibtp)
}

// Start mocks base method.
func (m *MockAdapt) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAdaptMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAdapt)(nil).Start))
}

// Stop mocks base method.
func (m *MockAdapt) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAdaptMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAdapt)(nil).Stop))
}
