// Code generated by MockGen. DO NOT EDIT.
// Source: bxh_adapter.go

// Package mock_bxhAdapt is a generated GoMock package.
package mock_bxhAdapt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pb "github.com/meshplus/bitxhub-model/pb"
)

// MockBxhAdapterI is a mock of BxhAdapterI interface.
type MockBxhAdapterI struct {
	ctrl     *gomock.Controller
	recorder *MockBxhAdapterIMockRecorder
}

// MockBxhAdapterIMockRecorder is the mock recorder for MockBxhAdapterI.
type MockBxhAdapterIMockRecorder struct {
	mock *MockBxhAdapterI
}

// NewMockBxhAdapterI creates a new mock instance.
func NewMockBxhAdapterI(ctrl *gomock.Controller) *MockBxhAdapterI {
	mock := &MockBxhAdapterI{ctrl: ctrl}
	mock.recorder = &MockBxhAdapterIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBxhAdapterI) EXPECT() *MockBxhAdapterIMockRecorder {
	return m.recorder
}

// GetBitXHubChainIDs mocks base method.
func (m *MockBxhAdapterI) GetBitXHubChainIDs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBitXHubChainIDs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBitXHubChainIDs indicates an expected call of GetBitXHubChainIDs.
func (mr *MockBxhAdapterIMockRecorder) GetBitXHubChainIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBitXHubChainIDs", reflect.TypeOf((*MockBxhAdapterI)(nil).GetBitXHubChainIDs))
}

// GetServiceIDList mocks base method.
func (m *MockBxhAdapterI) GetServiceIDList() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceIDList")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceIDList indicates an expected call of GetServiceIDList.
func (mr *MockBxhAdapterIMockRecorder) GetServiceIDList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceIDList", reflect.TypeOf((*MockBxhAdapterI)(nil).GetServiceIDList))
}

// ID mocks base method.
func (m *MockBxhAdapterI) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockBxhAdapterIMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockBxhAdapterI)(nil).ID))
}

// MonitorIBTP mocks base method.
func (m *MockBxhAdapterI) MonitorIBTP() chan *pb.IBTP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorIBTP")
	ret0, _ := ret[0].(chan *pb.IBTP)
	return ret0
}

// MonitorIBTP indicates an expected call of MonitorIBTP.
func (mr *MockBxhAdapterIMockRecorder) MonitorIBTP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorIBTP", reflect.TypeOf((*MockBxhAdapterI)(nil).MonitorIBTP))
}

// MonitorUpdatedMeta mocks base method.
func (m *MockBxhAdapterI) MonitorUpdatedMeta() chan *[]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorUpdatedMeta")
	ret0, _ := ret[0].(chan *[]byte)
	return ret0
}

// MonitorUpdatedMeta indicates an expected call of MonitorUpdatedMeta.
func (mr *MockBxhAdapterIMockRecorder) MonitorUpdatedMeta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorUpdatedMeta", reflect.TypeOf((*MockBxhAdapterI)(nil).MonitorUpdatedMeta))
}

// Name mocks base method.
func (m *MockBxhAdapterI) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockBxhAdapterIMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBxhAdapterI)(nil).Name))
}

// QueryIBTP mocks base method.
func (m *MockBxhAdapterI) QueryIBTP(id string, isReq bool) (*pb.IBTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryIBTP", id, isReq)
	ret0, _ := ret[0].(*pb.IBTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryIBTP indicates an expected call of QueryIBTP.
func (mr *MockBxhAdapterIMockRecorder) QueryIBTP(id, isReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryIBTP", reflect.TypeOf((*MockBxhAdapterI)(nil).QueryIBTP), id, isReq)
}

// QueryInterchain mocks base method.
func (m *MockBxhAdapterI) QueryInterchain(serviceID string) (*pb.Interchain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryInterchain", serviceID)
	ret0, _ := ret[0].(*pb.Interchain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryInterchain indicates an expected call of QueryInterchain.
func (mr *MockBxhAdapterIMockRecorder) QueryInterchain(serviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInterchain", reflect.TypeOf((*MockBxhAdapterI)(nil).QueryInterchain), serviceID)
}

// SendIBTP mocks base method.
func (m *MockBxhAdapterI) SendIBTP(ibtp *pb.IBTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendIBTP", ibtp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendIBTP indicates an expected call of SendIBTP.
func (mr *MockBxhAdapterIMockRecorder) SendIBTP(ibtp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendIBTP", reflect.TypeOf((*MockBxhAdapterI)(nil).SendIBTP), ibtp)
}

// SendUpdatedMeta mocks base method.
func (m *MockBxhAdapterI) SendUpdatedMeta(byte []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdatedMeta", byte)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdatedMeta indicates an expected call of SendUpdatedMeta.
func (mr *MockBxhAdapterIMockRecorder) SendUpdatedMeta(byte interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdatedMeta", reflect.TypeOf((*MockBxhAdapterI)(nil).SendUpdatedMeta), byte)
}

// Start mocks base method.
func (m *MockBxhAdapterI) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockBxhAdapterIMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBxhAdapterI)(nil).Start))
}

// Stop mocks base method.
func (m *MockBxhAdapterI) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockBxhAdapterIMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBxhAdapterI)(nil).Stop))
}
