// Code generated by MockGen. DO NOT EDIT.
// Source: checker.go

// Package mock_checker is a generated GoMock package.
package mock_checker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pb "github.com/meshplus/bitxhub-model/pb"
)

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// BasicCheck mocks base method.
func (m *MockChecker) BasicCheck(ibtp *pb.IBTP) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BasicCheck", ibtp)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BasicCheck indicates an expected call of BasicCheck.
func (mr *MockCheckerMockRecorder) BasicCheck(ibtp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BasicCheck", reflect.TypeOf((*MockChecker)(nil).BasicCheck), ibtp)
}

// CheckProof mocks base method.
func (m *MockChecker) CheckProof(ibtp *pb.IBTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProof", ibtp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckProof indicates an expected call of CheckProof.
func (mr *MockCheckerMockRecorder) CheckProof(ibtp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProof", reflect.TypeOf((*MockChecker)(nil).CheckProof), ibtp)
}
